#
#     Reputation+ 0.4
#     Author by pashavoid
#     File: database.yml
#

# Type: mysql / sqlite
type: mysql
# MySql IP address or domain
host: localhost
# MySQL name database
database: test
# MySQL username
username: root
# MySQL user password
password: root
# Do not touch the standard port. If a different port is used to connect to the database, specify it.
port: '3306'