name: ReputationPlus
author: pashavoid
description: Reputation for your server
main: ru.pashavoid.reputationplus.ReputationPlus
version: 0.4
api-version: 1.16
softdepend: [PlaceholderAPI]
commands:
  reputation:
    description: Opening GUI with Reputation
    usage: /<command>