name: ReputationPlus
author: pashavoid
description: Test Plugin
main: ru.pashavoid.reputationplus.ReputationPlus
version: 1.1
api-version: 1.16
commands:
  reputation:
    description: Opening GUI with Reputation
    usage: /<command>